# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FirebaseInstaClone' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'Firebase'
pod 'FirebaseAnalytics'
pod 'FirebaseAuth'
pod 'FirebaseFirestore'
pod 'FirebaseStorage'
pod 'Firebase/Analytics'
pod 'Firebase/Auth'
pod 'Firebase/Core'
pod 'Firebase/Messaging'
pod 'SDWebImage', '~> 5.0'


  # Pods for FirebaseInstaClone

end
